name       : python-configargparse
version    : 0.12.0
release    : 1
source     :
    - https://github.com/bw2/ConfigArgParse/archive/0.12.0.tar.gz : e47905425ebaeaf27f6fabe5e4db8e1206dc9772ebc4e0fb401ab9945cdd037b
license    : MIT
component  : programming.python
summary    : A drop-in replacement for argparse with config file support
description: |
    A drop-in replacement for argparse that allows options to also be set via config files and/or environment variables
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install