name       : python-configargparse
version    : 0.13.0
release    : 3
source     :
    - https://github.com/bw2/ConfigArgParse/archive/0.13.0.tar.gz : bfc2cce94cbd76c96a36ed901ff6b778a597f95f7ecbb909102288773ddeb0b8
license    : MIT
component  : programming.python
summary    : A drop-in replacement for argparse with config file support
description: |
    A drop-in replacement for argparse that allows options to also be set via config files and/or environment variables
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
