name       : python-configargparse
version    : 1.5.3
release    : 9
source     :
    - https://github.com/bw2/ConfigArgParse/archive/refs/tags/v1.5.3.tar.gz : 9eb08a295f5d89aed98c73b16b86ff0825cf64b45bf170c7fd4dbfbd44ad12be
license    : MIT
component  : programming.python
summary    : A drop-in replacement for argparse with config file support
description: |
    A drop-in replacement for argparse that allows options to also be set via config files and/or environment variables
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
