name       : python-configargparse
version    : 0.15.1
release    : 4
source     :
    - https://github.com/bw2/ConfigArgParse/archive/0.15.1.tar.gz : 40e7e60fe222a1c3679c878382b610a58c217483258a033ec8ed6cbd7ca3b870
license    : MIT
component  : programming.python
summary    : A drop-in replacement for argparse with config file support
description: |
    A drop-in replacement for argparse that allows options to also be set via config files and/or environment variables
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
