name       : python-configargparse
version    : 1.2.3
release    : 6
source     :
    - https://github.com/bw2/ConfigArgParse/archive/1.2.3.tar.gz : 0f1144a204e3b896d6ac900e151c1d13bde3103d6b7d541e3bb57514a94083bf
license    : MIT
component  : programming.python
summary    : A drop-in replacement for argparse with config file support
description: |
    A drop-in replacement for argparse that allows options to also be set via config files and/or environment variables
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
